// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hhYAirYt8bU9TEjNgFzExf
// Component: 27gvA1QUGfr
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: aZ_J2rMYPrG/component
import Section from "../../Section"; // plasmic-import: xpx1dd3WX7GW/component
import Button from "../../Button"; // plasmic-import: Tz4a3lVI6CGf/component
import FeatureCard from "../../FeatureCard"; // plasmic-import: 05tCG29nEfK/component
import Testimonial from "../../Testimonial"; // plasmic-import: uXYHN1Smh9Q/component
import Footer from "../../Footer"; // plasmic-import: tnj0d_eW4Ts/component

import { useScreenVariants as useScreenVariants_01LSGjai6PPg } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 01lSGjai6pPg/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_habistack_com.module.css"; // plasmic-import: hhYAirYt8bU9TEjNgFzExf/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: 27gvA1QUGfr/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 5jC4HENzcXyn/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: wruYgJ8FoWVC/icon
import LightningIcon from "./icons/PlasmicIcon__Lightning"; // plasmic-import: fR_M5TpK_IAp/icon
import HammerIcon from "./icons/PlasmicIcon__Hammer"; // plasmic-import: aos4xEgRa28Q/icon
import PencilIcon from "./icons/PlasmicIcon__Pencil"; // plasmic-import: TFB9T0WIMP-S/icon
import SwapIcon from "./icons/PlasmicIcon__Swap"; // plasmic-import: 8urSW3zsoVIf/icon
import SlotIcon from "./icons/PlasmicIcon__Slot"; // plasmic-import: hZBvhC7zZTr0/icon
import CycleIcon from "./icons/PlasmicIcon__Cycle"; // plasmic-import: sRQ2cmFxpNjv/icon
import FacebookLogoIcon from "./icons/PlasmicIcon__FacebookLogo"; // plasmic-import: w2kNC3zTGXKb/icon
import TinderLogoIcon from "./icons/PlasmicIcon__TinderLogo"; // plasmic-import: ZvTtjxYoOaFi/icon
import AirbnbLogoIcon from "./icons/PlasmicIcon__AirbnbLogo"; // plasmic-import: Ow2lAYtI17fS/icon
import HubspotLogoIcon from "./icons/PlasmicIcon__HubspotLogo"; // plasmic-import: UYcqQCUG5aJu/icon
import AmazonLogoIcon from "./icons/PlasmicIcon__AmazonLogo"; // plasmic-import: _SP557JjCvZu/icon

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  topSection?: p.Flex<typeof Section>;
  solutions?: p.Flex<typeof Section>;
  columns?: p.Flex<"div">;
  howItWorks?: p.Flex<typeof Section>;
  validation?: p.Flex<typeof Section>;
  testimonial?: p.Flex<typeof Testimonial>;
};

export interface DefaultHomeProps {
  dataFetches: PlasmicHome__Fetches;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  dataFetches?: PlasmicHome__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_01LSGjai6PPg()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <Section
            data-plasmic-name={"topSection"}
            data-plasmic-override={overrides.topSection}
            className={classNames("__wab_instance", sty.topSection)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___4Q2Ev)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__z4Bg)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__lCxli)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iQh5G
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Habistack"
                      : "Habistack"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__o1NKb
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Get the GroundTruth"
                      : "Get the GroundTruth"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lvLYp
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Simple, accurate weather forecasts for the world \nwe live in"
                    : "Simple, accurate weather forecasts\nfor the world we live in"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i2Ddb
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Currently undergoing maintenance and upgrades, your APIs will continue to work as expected."
                    : "Currently undergoing maintenance and upgrades, your \nAPIs will continue to work as expected."}
                </div>
              </p.Stack>

              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sajKs)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button___1ShE)}
                    color={"blue" as const}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__vFo1S)}
                        role={"img"}
                      />
                    }
                    showEndIcon={"showEndIcon" as const}
                  >
                    {"Start free trial"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__erBc)}
                  >
                    {"Learn more"}
                  </Button>
                </p.Stack>
              ) : null}

              <div className={classNames(projectcss.all, sty.freeBox__hg50H)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__kaKt7)}
                  displayHeight={"100%" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? ("100%" as const)
                      : ("632px /* plasmic-token: -_9hWElktusQ */" as const)
                  }
                  src={{
                    src: "/plasmic/habistack_com/images/microsoftTeamsImage7Png.png",
                    fullWidth: 1768,
                    fullHeight: 1722,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
          </Section>

          {true ? (
            <Section
              data-plasmic-name={"solutions"}
              data-plasmic-override={overrides.solutions}
              className={classNames("__wab_instance", sty.solutions)}
              hasSubtitle={"hasSubtitle" as const}
              hasTitle={"hasTitle" as const}
              subtitle={
                "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat."
              }
              title={"Explore the solutions"}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__fdgtj)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__cLgUs)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xYyGf
                      )}
                    >
                      {"Powerful suite of tools"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nuePw
                      )}
                    >
                      {
                        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa."
                      }
                    </div>

                    <FeatureCard
                      className={classNames(
                        "__wab_instance",
                        sty.featureCard__lPHD
                      )}
                      description={
                        "Taking collaboration to the next level with security and administrative features built for teams"
                      }
                      iconBack={
                        <LightningIcon
                          className={classNames(projectcss.all, sty.svg__kyj)}
                          role={"img"}
                        />
                      }
                      long={"long" as const}
                      title={"Building the Simple ecosystem"}
                    />

                    <FeatureCard
                      className={classNames(
                        "__wab_instance",
                        sty.featureCard__nWa2N
                      )}
                      description={
                        "Taking collaboration to the next level with security and administrative features built for teams"
                      }
                      iconBack={
                        <HammerIcon
                          className={classNames(projectcss.all, sty.svg__iLdLj)}
                          role={"img"}
                        />
                      }
                      long={"long" as const}
                      title={"Building the Simple Ecosystem"}
                    />

                    <FeatureCard
                      className={classNames(
                        "__wab_instance",
                        sty.featureCard__qR6Wr
                      )}
                      description={
                        "Taking collaboration to the next level with security and administrative features built for teams"
                      }
                      iconBack={
                        <PencilIcon
                          className={classNames(projectcss.all, sty.svg__qcTuh)}
                          role={"img"}
                        />
                      }
                      long={"long" as const}
                      title={"Building the Simple Ecosystem"}
                    />
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__wwTks)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__m9K3B)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    src={{
                      src: "/plasmic/habistack_com/images/simpleProject.png",
                      fullWidth: 1000,
                      fullHeight: 924,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </p.Stack>
            </Section>
          ) : null}
          {true ? (
            <Section
              data-plasmic-name={"howItWorks"}
              data-plasmic-override={overrides.howItWorks}
              className={classNames("__wab_instance", sty.howItWorks)}
              color={"halfDark" as const}
              hasSubtitle={"hasSubtitle" as const}
              hasTitle={"hasTitle" as const}
              subtitle={
                "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat."
              }
              title={"How Simple works"}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__fjHaL)}
              >
                <FeatureCard
                  className={classNames(
                    "__wab_instance",
                    sty.featureCard__yksoK
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                  }
                  iconFront={
                    <SwapIcon
                      className={classNames(projectcss.all, sty.svg__onGtd)}
                      role={"img"}
                    />
                  }
                  title={"Initial Contact"}
                />

                <FeatureCard
                  className={classNames(
                    "__wab_instance",
                    sty.featureCard__buzLn
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                  }
                  iconFront={
                    <SlotIcon
                      className={classNames(projectcss.all, sty.svg___5S0W6)}
                      role={"img"}
                    />
                  }
                  title={"Discovery Session"}
                />

                <FeatureCard
                  className={classNames(
                    "__wab_instance",
                    sty.featureCard__hujb9
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                  }
                  iconFront={
                    <CycleIcon
                      className={classNames(projectcss.all, sty.svg___9ViLc)}
                      role={"img"}
                    />
                  }
                  title={"Contracting"}
                />

                <FeatureCard
                  className={classNames(
                    "__wab_instance",
                    sty.featureCard__cdAs
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                  }
                  iconFront={
                    <HammerIcon
                      className={classNames(projectcss.all, sty.svg__yxKxy)}
                      role={"img"}
                    />
                  }
                  title={"Fast Prototyping"}
                />

                <FeatureCard
                  className={classNames(
                    "__wab_instance",
                    sty.featureCard__qNysj
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                  }
                  iconFront={
                    <PencilIcon
                      className={classNames(projectcss.all, sty.svg__kXkHf)}
                      role={"img"}
                    />
                  }
                  title={"Design Phase"}
                />

                <FeatureCard
                  className={classNames(
                    "__wab_instance",
                    sty.featureCard__fzMcq
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                  }
                  iconFront={
                    <LightningIcon
                      className={classNames(projectcss.all, sty.svg__xdR7J)}
                      role={"img"}
                    />
                  }
                  title={"Develop & Launch"}
                />
              </p.Stack>

              {true ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox__c3TgN)}
                />
              ) : null}
            </Section>
          ) : null}
          {true ? (
            <Section
              data-plasmic-name={"validation"}
              data-plasmic-override={overrides.validation}
              className={classNames("__wab_instance", sty.validation)}
              hasSubtitle={"hasSubtitle" as const}
              hasTitle={"hasTitle" as const}
              subtitle={
                "Arcu cursus vitae congue mauris rhoncus viverra nibh cras pulvinar mattis blandit libero cursus mattis."
              }
              title={"Trusted by over 20,000 companies all over the world"}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6Kou)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__n7AGr)}
                >
                  <FacebookLogoIcon
                    className={classNames(projectcss.all, sty.svg__b4EXb)}
                    role={"img"}
                  />

                  <TinderLogoIcon
                    className={classNames(projectcss.all, sty.svg__swWzK)}
                    role={"img"}
                  />

                  <AirbnbLogoIcon
                    className={classNames(projectcss.all, sty.svg__gIw98)}
                    role={"img"}
                  />

                  <HubspotLogoIcon
                    className={classNames(projectcss.all, sty.svg__nerzu)}
                    role={"img"}
                  />

                  <AmazonLogoIcon
                    className={classNames(projectcss.all, sty.svg__lKcPj)}
                    role={"img"}
                  />
                </p.Stack>

                <Testimonial
                  data-plasmic-name={"testimonial"}
                  data-plasmic-override={overrides.testimonial}
                  className={classNames("__wab_instance", sty.testimonial)}
                />
              </p.Stack>
            </Section>
          ) : null}
          {true ? (
            <Footer
              className={classNames("__wab_instance", sty.footer__rKGn)}
            />
          ) : null}

          <Footer
            className={classNames("__wab_instance", sty.footer___79PrO)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "topSection",
    "solutions",
    "columns",
    "howItWorks",
    "validation",
    "testimonial"
  ],
  header: ["header"],
  topSection: ["topSection"],
  solutions: ["solutions", "columns"],
  columns: ["columns"],
  howItWorks: ["howItWorks"],
  validation: ["validation", "testimonial"],
  testimonial: ["testimonial"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  topSection: typeof Section;
  solutions: typeof Section;
  columns: "div";
  howItWorks: typeof Section;
  validation: typeof Section;
  testimonial: typeof Testimonial;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHome__Fetches;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    topSection: makeNodeComponent("topSection"),
    solutions: makeNodeComponent("solutions"),
    columns: makeNodeComponent("columns"),
    howItWorks: makeNodeComponent("howItWorks"),
    validation: makeNodeComponent("validation"),
    testimonial: makeNodeComponent("testimonial"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
